#!/bin/bash
# shellcheck source=/dev/null
source "${HOME}/.git-friends/src/url.sh"
source "${HOME}/.git-friends/src/utility.sh"

exec < /dev/tty

name="${1:-origin}"

if url="$(git config --get "remote.${name}.url" 2>/dev/null)"; then
  # protocol="$(git::url::parse "${url}" 1)"
  base_url="$(git::url::parse "${url}" 2)"
  user="$(git::url::parse "${url}" 4)"
  repo="$(git::url::parse "${url}" 5)"
  https_url="https://${base_url}/${user}/${repo}"

  if git::utility::ask "convert remote ${name}: ${url} to ~~~> ${https_url}"; then
    git remote set-url "${name}" "${https_url}"
  fi
else
  >&2 echo "ERROR: remote '${name}' not found"
  exit 1
fi
