#!/bin/bash
# shellcheck source=/dev/null
source "${HOME}/.git-friends/src/url.sh"
source "${HOME}/.git-friends/src/utility.sh"

exec < /dev/tty

remote="${1:-origin}"

if ! url="$(git config --get "remote.${remote}.url" 2>/dev/null)"; then
  >&2 echo "ERROR: remote '${remote}' not found"
  exit 1
fi

if new_url="$(git::url::change_protocol "${url}" 'https')" \
  && git::utility::ask "convert remote ${remote}: ${url} to ~~~> ${new_url}"; then
    git remote set-url "${remote}" "${new_url}"
fi
